trigger:
  - master

variables:
  DOTNET_SDK_VERSION: "3.1.402"

pool:
  vmImage: "windows-2019"

steps:
  - checkout: self
    submodules: true

  - task: UseDotNet@2
    displayName: "Use .NET Core SDK $(DOTNET_SDK_VERSION)"
    inputs:
      version: "$(DOTNET_SDK_VERSION)"

  - task: NuGetAuthenticate@0
    displayName: "NuGet Authenticate"

  - powershell: ./build.ps1 --target VSTS
    displayName: "Execute Cake Build"
    env:
      NUGET_URL: PulseInc
      NUGET_API_KEY: az
