name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Get the sources
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v1.1.2
        with:
          path: tools
          key: ${{ runner.os }}-${{ hashFiles('build/**') }}
      - name: Run Cake script
        run: ./build.ps1 --target GitHub
        shell: powershell
        env:
          NUGET_URL: https://api.nuget.org/v3/index.json
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
