name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Get the sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache Cake Tools
        uses: actions/cache@v1.1.2
        with:
          path: tools
          key: ${{ runner.os }}-${{ hashFiles('build/**') }}
      - name: Cache Nugets
        uses: actions/cache@v1.1.2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Run Cake script
        run: ./build.ps1 --target GitHub
        shell: powershell
        env:
          NUGET_URL: https://api.nuget.org/v3/index.json
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}

      - uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: binaries
          path: artifacts/bin
      - uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: test-reports
          path: artifacts/test-reports
      - uses: actions/upload-artifact@v2
        with:
          name: nugets
          path: artifacts/nuget

  analyze:
    needs: build
    runs-on: windows-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-reports
          name: Tests
          path: "*.trx"
          reporter: dotnet-trx
